// <auto-generated />
using System;
using DiscountAggregator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiscountAggregator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250916071523_RemoveUserProductSubscriptionsAndAddUserCategorySubscriptions")]
    partial class RemoveUserProductSubscriptionsAndAddUserCategorySubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);


            modelBuilder.Entity("DiscountAggregator.Domain.Entities.Product", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");


                b.Property<string>("Brand")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)");


                b.Property<decimal>("CurrentPrice")
                    .HasColumnType("numeric");


                b.Property<string>("ExternalId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");


                b.Property<DateTime>("LastUpdatedAtUtc")
                    .HasColumnType("timestamp with time zone");


                b.Property<decimal>("OldPrice")
                    .HasColumnType("numeric");


                b.Property<string>("Source")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");


                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)");


                b.Property<string>("Url")
                    .IsRequired()
                    .HasMaxLength(1024)
                    .HasColumnType("character varying(1024)");


                b.HasKey("Id");


                b.HasIndex("Source", "ExternalId")
                    .IsUnique();


                b.ToTable("Products");
            });


            modelBuilder.Entity("DiscountAggregator.Domain.Entities.ProductPriceHistory", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");


                b.Property<decimal>("Price")
                    .HasColumnType("numeric");


                b.Property<Guid>("ProductId")
                    .HasColumnType("uuid");


                b.Property<DateTime>("RecordedAtUtc")
                    .HasColumnType("timestamp with time zone");


                b.HasKey("Id");


                b.HasIndex("ProductId", "RecordedAtUtc");


                b.ToTable("ProductPriceHistories");
            });


            modelBuilder.Entity("DiscountAggregator.Domain.Entities.SearchQuery", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");


                b.Property<string>("Keyword")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");


                b.Property<string>("KeywordNormalized")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");


                b.Property<DateTime>("QueriedAtUtc")
                    .HasColumnType("timestamp with time zone");


                b.Property<string>("SourceFilter")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");


                b.Property<long>("UserId")
                    .HasColumnType("bigint");


                b.HasKey("Id");


                b.HasIndex("UserId", "QueriedAtUtc");


                b.ToTable("SearchQueries");
            });


            modelBuilder.Entity("DiscountAggregator.Domain.Entities.User", b =>
            {
                b.Property<long>("Id")
                    .HasColumnType("bigint");


                b.Property<DateTime>("LastActivityAtUtc")
                    .HasColumnType("timestamp with time zone");


                b.Property<DateTime>("RegisteredAtUtc")
                    .HasColumnType("timestamp with time zone");


                b.Property<string>("Username")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");


                b.HasKey("Id");


                b.HasIndex("LastActivityAtUtc");


                b.ToTable("Users");
            });


            modelBuilder.Entity("DiscountAggregator.Domain.Entities.UserCategorySubscription", b =>
            {
                b.Property<long>("UserId")
                    .HasColumnType("bigint");


                b.Property<string>("Keyword")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");


                b.Property<string>("SourceFilter")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");


                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");


                b.Property<DateTime>("SubscribedAtUtc")
                    .HasColumnType("timestamp with time zone");


                b.HasKey("UserId", "Keyword", "SourceFilter");


                b.HasIndex("UserId", "IsActive");


                b.ToTable("UserCategorySubscriptions");
            });


            modelBuilder.Entity("DiscountAggregator.Domain.Entities.ProductPriceHistory", b =>
            {
                b.HasOne("DiscountAggregator.Domain.Entities.Product", "Product")
                    .WithMany("PriceHistory")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();


                b.Navigation("Product");
            });


            modelBuilder.Entity("DiscountAggregator.Domain.Entities.SearchQuery", b =>
            {
                b.HasOne("DiscountAggregator.Domain.Entities.User", "User")
                    .WithMany("SearchHistory")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();


                b.Navigation("User");
            });


            modelBuilder.Entity("DiscountAggregator.Domain.Entities.UserCategorySubscription", b =>
            {
                b.HasOne("DiscountAggregator.Domain.Entities.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();


                b.Navigation("User");
            });


            modelBuilder.Entity("DiscountAggregator.Domain.Entities.Product", b =>
            {
                b.Navigation("PriceHistory");
            });


            modelBuilder.Entity("DiscountAggregator.Domain.Entities.User", b =>
            {
                b.Navigation("SearchHistory");
            });
#pragma warning restore 612, 618
        }
    }
}

